# NumPy Review Challenge

To review some basic concepts, attempt to perform these basic NumPy tasks on your own and then watch the walkthrough video to check your solutions.

Once your assignment is complete and you have watched the solution video to check your answers, make sure that you save it as `numpy_review` and upload it to CodeGrade to get credit for your work.

Import numpy as np and check your version.

In [3]:
#standard import
import numpy as np
print(np.__version__)

1.26.4


**Q1:** Create a 1D array of numbers from `0` to `9` and save it as `Q1`.

In [5]:
#Q1
Q1 = np.arange(10)
Q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Q2:** Create a 1D array of numbers from `10` to `49` and save it as `Q2`.

In [9]:
#Q2
Q2 = np.arange(10,50)
Q2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**Q3:** Copy the `Q2` array and save it as `Q3`.  Reverse the values in the `Q3` array (first element becomes the last, last becomes the first, etc).

In [11]:
# make a copy of the previous array to prevent a "view" from being created
Q3 = Q2.copy()

Q3 = Q3[::-1]
Q3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Q4:** Create a `3x3` matrix with values ranging from `1` to `9` and save it as `Q4`.

In [15]:
#Q4
Q4 = np.arange(1,10).reshape(3,3)
Q4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Q5:** Using the [Random Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator), set a random seed of `42`. Create a `10x5` array with random values and save it as `Q5`.  Use `random` as shown in the example in the documentation linked above.  This may be new for some of you, but the documentation does a good job of explaining it. As a check, your first row of the array should be: `[0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735]`

In [17]:
#Q5
rng = np.random.default_rng(seed=42) 

Q5 = rng.random((10, 5))
Q5

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735],
       [0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594],
       [0.37079802, 0.92676499, 0.64386512, 0.82276161, 0.4434142 ],
       [0.22723872, 0.55458479, 0.06381726, 0.82763117, 0.6316644 ],
       [0.75808774, 0.35452597, 0.97069802, 0.89312112, 0.7783835 ],
       [0.19463871, 0.466721  , 0.04380377, 0.15428949, 0.68304895],
       [0.74476216, 0.96750973, 0.32582536, 0.37045971, 0.46955581],
       [0.18947136, 0.12992151, 0.47570493, 0.22690935, 0.66981399],
       [0.43715192, 0.8326782 , 0.7002651 , 0.31236664, 0.8322598 ],
       [0.80476436, 0.38747838, 0.2883281 , 0.6824955 , 0.13975248]])

**Q6:** Find the minimum and maximum values of above `Q5` array, rounding them to 4 decimal places.  Call the values `Q6A` and `Q6B` respectively. 

In [19]:
#Q6A
Q6A = round(Q5.min(), 4)
Q6A

0.0438

In [21]:
#Q6B
Q6B = round(Q5.max(), 4)
Q6B

0.9756

**Q7:** Find the mean value for the above `Q5` array, rounding to 4 decimal places.  Call this value `Q7`.

In [23]:
#Q7
Q7 = round(Q5.mean(), 4)
Q7

0.5352

**Q8:** Select all even numbers from the following array and call this output `Q8`.
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [25]:
#Q8
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q8 = arr[arr % 2 == 0]
Q8

array([0, 2, 4, 6, 8])

**Q9:** Make a copy of the `arr` array and call it `Q9`.  Replace all even numbers from `Q9` with `0`.

In [27]:
#Q9
Q9 = arr.copy()

Q9[Q9 % 2 == 0] = 0
Q9

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

**Q10:** Use the [where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) method to replace all odd numbers from the above `Q9` array with a `-1` and call it `Q10`.

In [29]:
#Q10
Q10 = np.where(Q9 % 2 == 1, -1, Q9)
Q10

array([ 0, -1,  0, -1,  0, -1,  0, -1,  0, -1])

**Q11** Reshape the above `arr` array to a `2x5` array and call it `Q11`.

In [31]:
#Q11
Q11 = arr.reshape((2,5))
Q11

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Q12:** Stack `arr1` and `arr2` (both given below) vertically and call this array `Q12`.

In [33]:
arr1 = np.arange(10).reshape((2,5))
arr2 = np.arange(10,20).reshape((2,5))

Q12 = np.concatenate([arr1, arr2], axis=0)
Q12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Q13:** Stack `arr1` and `arr2` horizontally and call this array `Q13`.

In [35]:
#Q13
Q13 = np.concatenate([arr1, arr2], axis=1)
Q13

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

**Q14:** Swap the first and second columns in the following array called `arr3` and save it as `Q14`.

In [37]:
# original array
arr3 = np.array([22,56,34,54,12,42,67,56,99]).reshape((3,3))
arr3

array([[22, 56, 34],
       [54, 12, 42],
       [67, 56, 99]])

In [39]:
# Q14
Q14 = arr3[:, [1,0,2]]
Q14

array([[56, 22, 34],
       [12, 54, 42],
       [56, 67, 99]])

**Q15:** Swap the first row and the second row in the above `Q14` array and call it `Q15`.

In [41]:
#Q15
Q15 = Q14[[1,0,2], :]
Q15

array([[12, 54, 42],
       [56, 22, 34],
       [56, 67, 99]])

**Q16:** Next, reverse the columns of the above `Q15` array and call it `Q16`.

In [43]:
#Q16
Q16 = Q15[:, ::-1]
Q16

array([[42, 54, 12],
       [34, 22, 56],
       [99, 67, 56]])

**Q17:** Sort each row of the above `Q16` array from least to greatest and call it `Q17`.

In [45]:
#Q17
Q17 = np.sort(Q16, axis=1)
Q17

array([[12, 42, 54],
       [22, 34, 56],
       [56, 67, 99]])

**Q18:** Sort each column of the above `Q17` array from the least to the greatest and call it `Q18`.

In [47]:
#Q18
Q18 = np.sort(Q17, axis=0)
Q18

array([[12, 34, 54],
       [22, 42, 56],
       [56, 67, 99]])

**Q19:** Create a `1D` array called `Q19` of `100` values that range evenly between `[1 - 200]`.


In [49]:
#Q19
Q19 = np.linspace(1,200,100)
Q19

array([  1.        ,   3.01010101,   5.02020202,   7.03030303,
         9.04040404,  11.05050505,  13.06060606,  15.07070707,
        17.08080808,  19.09090909,  21.1010101 ,  23.11111111,
        25.12121212,  27.13131313,  29.14141414,  31.15151515,
        33.16161616,  35.17171717,  37.18181818,  39.19191919,
        41.2020202 ,  43.21212121,  45.22222222,  47.23232323,
        49.24242424,  51.25252525,  53.26262626,  55.27272727,
        57.28282828,  59.29292929,  61.3030303 ,  63.31313131,
        65.32323232,  67.33333333,  69.34343434,  71.35353535,
        73.36363636,  75.37373737,  77.38383838,  79.39393939,
        81.4040404 ,  83.41414141,  85.42424242,  87.43434343,
        89.44444444,  91.45454545,  93.46464646,  95.47474747,
        97.48484848,  99.49494949, 101.50505051, 103.51515152,
       105.52525253, 107.53535354, 109.54545455, 111.55555556,
       113.56565657, 115.57575758, 117.58585859, 119.5959596 ,
       121.60606061, 123.61616162, 125.62626263, 127.63

**Q20:** Reshape `Q19` to a `25x4` array and call it `Q20`.

In [51]:
#Q20
Q20 = Q19.reshape(25,4)
Q20

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [  9.04040404,  11.05050505,  13.06060606,  15.07070707],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 25.12121212,  27.13131313,  29.14141414,  31.15151515],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 41.2020202 ,  43.21212121,  45.22222222,  47.23232323],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

**Q21:** Index the first row of `Q20` and save this as `Q21`.

In [53]:
#Q21
Q21 = Q20[0]
Q21

array([1.        , 3.01010101, 5.02020202, 7.03030303])

**Q22:** Index the second column of `Q20` and save this as `Q22`.

In [55]:
#Q22
Q22 = Q20[:,1]
Q22

array([  3.01010101,  11.05050505,  19.09090909,  27.13131313,
        35.17171717,  43.21212121,  51.25252525,  59.29292929,
        67.33333333,  75.37373737,  83.41414141,  91.45454545,
        99.49494949, 107.53535354, 115.57575758, 123.61616162,
       131.65656566, 139.6969697 , 147.73737374, 155.77777778,
       163.81818182, 171.85858586, 179.8989899 , 187.93939394,
       195.97979798])

**Q23:** Index every other row of `Q20` starting from the first and save this as `Q23`.

In [57]:
#Q23
Q23 = Q20[::2]
Q23

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [129.64646465, 131.65656566, 133.66666667, 135.67676768],
       [145.72727273, 147.73737374, 149.74747475, 151.75757576],
       [161.80808081, 163.81818182, 165.82828283, 167.83838384],
       [177.88888889, 179.8989899 , 181.90909091, 183.91919192],
       [193.96969697, 195.97979798, 197.98989899, 200.        ]])

**Q24**: Add `1` to every element in `Q20` and call the new array `Q24`.

In [59]:
Q24 = Q20 + 1
Q24

array([[  2.        ,   4.01010101,   6.02020202,   8.03030303],
       [ 10.04040404,  12.05050505,  14.06060606,  16.07070707],
       [ 18.08080808,  20.09090909,  22.1010101 ,  24.11111111],
       [ 26.12121212,  28.13131313,  30.14141414,  32.15151515],
       [ 34.16161616,  36.17171717,  38.18181818,  40.19191919],
       [ 42.2020202 ,  44.21212121,  46.22222222,  48.23232323],
       [ 50.24242424,  52.25252525,  54.26262626,  56.27272727],
       [ 58.28282828,  60.29292929,  62.3030303 ,  64.31313131],
       [ 66.32323232,  68.33333333,  70.34343434,  72.35353535],
       [ 74.36363636,  76.37373737,  78.38383838,  80.39393939],
       [ 82.4040404 ,  84.41414141,  86.42424242,  88.43434343],
       [ 90.44444444,  92.45454545,  94.46464646,  96.47474747],
       [ 98.48484848, 100.49494949, 102.50505051, 104.51515152],
       [106.52525253, 108.53535354, 110.54545455, 112.55555556],
       [114.56565657, 116.57575758, 118.58585859, 120.5959596 ],
       [122.60606061, 124

**Q25:** 
- Make a copy of the `Q24` array and call it `Q25`.  
- Select the first value in the first 5 rows in `Q25` and call this slice `arr_slice`.
- Update the second value in `arr_slice` to `42`. Before you check the results, will this update `Q25` or will it remain unchanged?

In [61]:
Q25 = Q24.copy()

arr_slice = Q25[0:5,0]
arr_slice

array([ 2.        , 10.04040404, 18.08080808, 26.12121212, 34.16161616])

In [63]:
arr_slice[1] = 42

In [65]:
Q25

array([[  2.        ,   4.01010101,   6.02020202,   8.03030303],
       [ 42.        ,  12.05050505,  14.06060606,  16.07070707],
       [ 18.08080808,  20.09090909,  22.1010101 ,  24.11111111],
       [ 26.12121212,  28.13131313,  30.14141414,  32.15151515],
       [ 34.16161616,  36.17171717,  38.18181818,  40.19191919],
       [ 42.2020202 ,  44.21212121,  46.22222222,  48.23232323],
       [ 50.24242424,  52.25252525,  54.26262626,  56.27272727],
       [ 58.28282828,  60.29292929,  62.3030303 ,  64.31313131],
       [ 66.32323232,  68.33333333,  70.34343434,  72.35353535],
       [ 74.36363636,  76.37373737,  78.38383838,  80.39393939],
       [ 82.4040404 ,  84.41414141,  86.42424242,  88.43434343],
       [ 90.44444444,  92.45454545,  94.46464646,  96.47474747],
       [ 98.48484848, 100.49494949, 102.50505051, 104.51515152],
       [106.52525253, 108.53535354, 110.54545455, 112.55555556],
       [114.56565657, 116.57575758, 118.58585859, 120.5959596 ],
       [122.60606061, 124

Good work!